# Generated by Django 3.0.5 on 2020-04-09 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('date_posted', models.DateTimeField()),
                ('post_desc', models.CharField(max_length=150)),
                ('post_title', models.CharField(max_length=50)),
                ('work_in_progress', models.BooleanField()),
            ],
        ),
    ]
