# Generated by Django 3.0.5 on 2020-04-16 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200414_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='post_link',
            field=models.CharField(default='google.com', max_length=200),
        ),
    ]
