# Generated by Django 3.0.5 on 2020-04-16 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projects_post_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='post_link',
            field=models.CharField(default='', max_length=200),
        ),
    ]
